name: test_task_eclipt
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  get_it: ^8.2.0
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  logger: ^2.6.1
  rxdart: ^0.28.0
  flutter_native_splash: ^2.4.6
  spider: ^4.2.2
  flutter_bloc: ^9.1.1
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  json_serializable: ^6.11.1
  json_annotation: ^4.9.0
  flutter_toastr: ^1.0.3
  fluttertoast: ^8.2.12
  build_runner: ^2.8.0
  flutter_svg: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  dart_style: any

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/font/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/font/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/font/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/font/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/font/Montserrat-Light.ttf
          weight: 300
        - asset: assets/font/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/font/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/font/Montserrat-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/font/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/font/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/font/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/font/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/font/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/font/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/font/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/font/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/font/Montserrat-Black.ttf
          weight: 900
        - asset: assets/font/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
